services:
  # 后端服务
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    container_name: system-monitor-backend
    restart: always
    networks:
      - app-network
    privileged: true  # 保留特权模式
    volumes:
      - /proc:/host/proc:ro  # 保留挂载宿主机目录
      - /sys:/host/sys:ro
    ports:
      - "8000:8000"  # 暴露端口到宿主机
    # 添加健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/system/cpu"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # 前端服务
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
    container_name: system-monitor-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 